#!/usr/bin/env node
// Builds src/live2d/viewerHtml.ts from fi005-live2d-ai's generated viewer.
//
//   node tools/live2d/build_viewer.mjs ../furia/fi005-live2d-ai/src/live2d/viewerHtml.ts
//
// fi005 inlines the Live2D Cubism Core into the page. The Core is proprietary
// Live2D code, "Redistributable Code" that may ship inside an app. This
// repository is public, so it is not committed here: the page loads the Core
// from Live2D's own CDN instead, the same file byte for byte. The rest of the
// page (Cubism Framework 5 and fi005's viewer) is kept as-is.
import fs from "node:fs";

const CORE_URL = "https://cubism.live2d.com/sdk-web/cubismcore/live2dcubismcore.min.js";
const src = process.argv[2];
if (!src) {
    console.error("usage: build_viewer.mjs <fi005 src/live2d/viewerHtml.ts>");
    process.exit(1);
}

const ts = fs.readFileSync(src, "utf8");
const m = ts.match(/export const VIEWER_HTML = (".*");?\s*$/s);
if (!m) throw new Error("VIEWER_HTML literal not found");
let html = JSON.parse(m[1]);

const scripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];
const core = scripts.find((s) => /Live2D Cubism Core/.test(s[1].slice(0, 400)));
if (!core) throw new Error("no inlined Cubism Core found; has the fi005 build changed?");

// Synchronous on purpose: the viewer script right after it expects
// Live2DCubismCore to exist when it runs. If the CDN cannot be reached, the
// page reports it the same way it reports a model that fails to load.
const tag =
    `<script src="${CORE_URL}" onerror="(window.ReactNativeWebView||{postMessage(){}}).postMessage(` +
    `JSON.stringify({type:'error',message:'cubism core unavailable'}))"></script>`;
html = html.replace(core[0], tag);

const out =
    "// AUTO-GENERATED by tools/live2d/build_viewer.mjs from fi005-live2d-ai — do not edit.\n" +
    "// The Cubism Core is loaded from Live2D's CDN, not bundled; see that script.\n" +
    `export const VIEWER_HTML = ${JSON.stringify(html)};\n`;
fs.writeFileSync(new URL("../../src/live2d/viewerHtml.ts", import.meta.url), out);
console.log(`viewerHtml.ts: ${(out.length / 1024).toFixed(0)} KB (Core removed: ${(core[1].length / 1024).toFixed(0)} KB)`);
