#!/usr/bin/env python3
"""
Generate the SQL that adds the fi005 Live2D characters to TrueMate.

Input is a JSON dump of fi005's `characters` table (select * where
is_active). The output is idempotent: rows reuse fi005's ids, so running it
again updates them instead of adding copies.

Run:  python3 tools/live2d/seed_sql.py /tmp/l2d_chars.json > supabase/migrations/<ts>_live2d_characters.sql
"""
import json
import sys

STORAGE = "https://kwqqmjfsrgoczbutuisx.supabase.co/storage/v1/object/public/live2d/"
DEFAULT_BACKGROUND = "0a63ecc7-4478-467c-b46e-9a9146e01d27"

# Listed in the app, and how each one is sold. Exactly one Live2D girl is free.
# The others follow TrueMate's PRO pattern: PRO, or bought with ruby. The male
# characters and the pet are copied but not listed, since this is a girlfriend
# app; the CMS can list them later by setting data.live2d_listed.
PLAN = {
    "hiyori": {"listed": True,  "tier": "free", "price": None},
    "haru":   {"listed": True,  "tier": "pro",  "price": 1000},
    "mao":    {"listed": True,  "tier": "pro",  "price": 1000},
    "rice":   {"listed": True,  "tier": "pro",  "price": 1000},
    "natori": {"listed": False, "tier": "pro",  "price": 1000},
    "mark":   {"listed": False, "tier": "pro",  "price": 1000},
    "wanko":  {"listed": False, "tier": "pro",  "price": 1000},
}

# Picker order within the Live2D group: the free one first, as the way in.
ORDER = {"hiyori": "000", "mao": "0001", "haru": "0002", "rice": "0003"}

# fi005 lays her out beside a side rail. TrueMate centres the character.
OFFSET_X = {"rice": -0.55}

TAGLINES = {
    "hiyori": {
        "vi": "Cô nàng hàng xóm ngọt ngào, mê cà phê và hoa",
        "ja": "カフェと花が大好きな、となりの優しい女の子",
        "ko": "카페와 꽃을 좋아하는 다정한 옆집 소녀",
        "zh": "爱咖啡馆和鲜花的甜美邻家女孩",
        "de": "Das süße Mädchen von nebenan, das Cafés und Blumen liebt",
        "es": "La dulce chica de al lado que ama las cafeterías y las flores",
        "fr": "La douce voisine qui adore les cafés et les fleurs",
        "it": "La dolce ragazza della porta accanto che ama i caffè e i fiori",
        "pt": "A doce garota da casa ao lado que ama cafés e flores",
    },
    "haru": {
        "vi": "Cô tiếp viên hàng không nhiều chuyện để kể",
        "ja": "話題が尽きない、客室乗務員の彼女",
        "ko": "이야깃거리가 가득한 승무원 여자친구",
        "zh": "满肚子故事的空姐女友",
        "de": "Flugbegleiterin mit einem Koffer voller Geschichten",
        "es": "Tu novia azafata, llena de historias",
        "fr": "Ta petite amie hôtesse de l'air, pleine d'histoires",
        "it": "La tua ragazza assistente di volo, piena di storie",
        "pt": "Sua namorada comissária de bordo, cheia de histórias",
    },
    "mao": {
        "vi": "Phù thuỷ tập sự tinh nghịch, mê đồ ngọt",
        "ja": "甘いもの好きな、いたずらっ子の魔女見習い",
        "ko": "달콤한 걸 좋아하는 장난꾸러기 견습 마녀",
        "zh": "爱吃甜食的调皮见习魔女",
        "de": "Freche Hexenlehrling mit einer Schwäche für Süßes",
        "es": "Aprendiz de bruja traviesa y golosa",
        "fr": "Apprentie sorcière espiègle et gourmande",
        "it": "Apprendista strega birichina e golosa",
        "pt": "Aprendiz de bruxa travessa e formiguinha",
    },
    "rice": {
        "vi": "Pháp sư dịu dàng, mê sách và ngắm sao",
        "ja": "本と星空を愛する、優しく好奇心旺盛な魔法使い",
        "ko": "책과 별을 사랑하는 다정하고 호기심 많은 마법사",
        "zh": "温柔又好奇、热爱书本和星空的魔法师",
        "de": "Sanfte, neugierige Magierin, die Bücher und Sterne liebt",
        "es": "Maga dulce y curiosa que ama los libros y las estrellas",
        "fr": "Magicienne douce et curieuse, amoureuse des livres et des étoiles",
        "it": "Maga dolce e curiosa che ama i libri e le stelle",
        "pt": "Maga gentil e curiosa que ama livros e estrelas",
    },
}


def q(v):
    """SQL literal."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, (dict, list)):
        return q(json.dumps(v, ensure_ascii=False)) + "::jsonb"
    return "'" + str(v).replace("'", "''") + "'"


def instruction(c):
    lines = [c["persona"].strip()]
    if c.get("bio"):
        lines.append(f"About you: {c['bio'].strip()}")
    if c.get("likes"):
        lines.append("You like: " + ", ".join(c["likes"]) + ".")
    if c.get("dislikes"):
        lines.append("You dislike: " + ", ".join(c["dislikes"]) + ".")
    if c.get("birthday"):
        lines.append(f"Your birthday is {c['birthday']} (MM-DD).")
    return "\n\n".join(lines)


def main(path):
    rows = json.load(open(path))
    out = [
        "-- Live2D characters, copied from fi005 (glzsmmijnywamdlinvlr).",
        "-- Generated by tools/live2d/seed_sql.py; model files copied by",
        "-- tools/live2d/clone_characters.py into the public `live2d` bucket.",
        "--",
        "-- available = false on purpose. Every character query in the builds",
        "-- already on the store requires `available` (or data.coming_soon), so",
        "-- they never see these and never try to open a model3.json as a VRM.",
        "-- Builds that render Live2D list them by data.model_type and",
        "-- data.live2d_listed instead. is_public stays true because RLS only lets",
        "-- clients read public rows.",
        "",
    ]
    for c in rows:
        slug = c["slug"]
        plan = PLAN[slug]
        thumb = STORAGE + f"thumbs/{slug}.png"
        data = {
            # The same profile fields the VRM characters carry, so the preview
            # reads one shape for both kinds.
            "old": c.get("age"),
            "hobbies": c.get("likes") or [],
            "dislikes": c.get("dislikes") or [],
            "bio": c.get("bio"),
            "bio_vi": c.get("bio_vi"),
            "birthday": c.get("birthday"),
            "model_type": "live2d",
            "live2d_listed": plan["listed"],
            "live2d_source": f"fi005:{slug}",
            "live2d": {
                "model_url": STORAGE + c["model_path"],
                "scale": c["scale"],
                "offset_x": OFFSET_X.get(slug, c.get("offset_x") or 0),
                "offset_y": c.get("offset_y") or 0,
                "emotion_map": c.get("emotion_map") or {},
                "action_map": c.get("action_map") or {},
                "outfits": c.get("outfits"),
                "accessories": c.get("accessories") or [],
                "voice_id": c.get("voice_id"),
                "greeting": c.get("greeting"),
                "greeting_vi": c.get("greeting_vi"),
                "theme": c.get("theme"),
            },
        }
        out.append(
            "insert into characters (id, name, description, instruction, is_public, available, tier, "
            "price_ruby, thumbnail_url, small_thumb_url, avatar, small_avatar, avatar_nobg, base_model_url, "
            "background_default_id, \"order\", difficulty, data)\nvalues ("
            + ", ".join([
                q(c["id"]), q(c["name"]), q(c["tagline"]), q(instruction(c)), "true", "false",
                q(plan["tier"]), q(plan["price"]), q(thumb), q(thumb), q(thumb), q(thumb), q(thumb),
                "null", q(DEFAULT_BACKGROUND), q(ORDER.get(slug, "0009")), "2", q(data),
            ])
            + ")\non conflict (id) do update set name = excluded.name, description = excluded.description, "
            "instruction = excluded.instruction, tier = excluded.tier, price_ruby = excluded.price_ruby, "
            "thumbnail_url = excluded.thumbnail_url, small_thumb_url = excluded.small_thumb_url, "
            "avatar = excluded.avatar, small_avatar = excluded.small_avatar, avatar_nobg = excluded.avatar_nobg, "
            "\"order\" = excluded.\"order\", data = excluded.data;\n"
        )
        for lang, text in TAGLINES.get(slug, {}).items():
            out.append(
                "insert into character_translates (character_id, language_code, name, description) values ("
                + ", ".join([q(c["id"]), q(lang), q(c["name"]), q(text)])
                + ") on conflict (character_id, language_code) do update set description = excluded.description, updated_at = now();"
            )
        if slug in TAGLINES:
            out.append(
                "insert into character_translates (character_id, language_code, name, description) values ("
                + ", ".join([q(c["id"]), q("en"), q(c["name"]), q(c["tagline"])])
                + ") on conflict (character_id, language_code) do update set description = excluded.description, updated_at = now();\n"
            )
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
