import { StyleSheet } from "react-native";

/** Styles for SubscriptionSheet — split out to keep the component under 1000 lines. */
export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#000" },
    contentWrap: { flex: 1 },
    header: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        zIndex: 20,
        flexDirection: "row",
        justifyContent: "flex-end",
        paddingHorizontal: 20,
    },
    closeBtn: { overflow: "hidden", borderRadius: 20 },
    closeBtnInner: { width: 40, height: 40, alignItems: "center", justifyContent: "center" },
    mainContent: { flex: 1, zIndex: 10 },
    scrollContent: { paddingTop: 100, paddingHorizontal: 24, paddingBottom: 40 },

    finePrint: {
        color: "rgba(255,255,255,0.45)",
        fontSize: 11.5,
        lineHeight: 16,
        marginTop: 12,
        paddingHorizontal: 4,
    },

    // Hero
    heroSection: { marginBottom: 28, alignItems: "center" },
    proBadge: {
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderRadius: 12,
        marginBottom: 16,
    },
    proBadgeText: { color: "#fff", fontSize: 12, fontWeight: "800", letterSpacing: 1 },
    heroTitle: {
        color: "#fff",
        fontSize: 26,
        fontWeight: "900",
        lineHeight: 32,
        textAlign: "center",
        marginBottom: 18,
        textShadowColor: "rgba(0,0,0,0.5)",
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 10,
    },

    // Demo Controls
    demoControls: {
        width: "100%",
        alignItems: "stretch",
        marginBottom: 24,
        gap: 16,
    },
    avatarGlassPill: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255,255,255,0.06)",
        borderRadius: 40,
        paddingVertical: 6,
        paddingHorizontal: 8,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.08)",
    },
    carouselList: { flexGrow: 0 },
    arrowBtn: { padding: 8 },
    thumbnailList: { flexGrow: 1, gap: 10, paddingHorizontal: 4, alignItems: "center", justifyContent: "center" },
    thumbnailWrap: {
        width: 50,
        height: 50,
        borderRadius: 25,
        justifyContent: "center",
        alignItems: "center",
        overflow: "hidden",
        borderWidth: 2,
        borderColor: "rgba(150, 100, 255, 0.2)",
    },
    thumbnailWrapActive: {
        borderColor: "#9B59FF",
        borderWidth: 2.5,
        shadowColor: "#9B59FF",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.7,
        shadowRadius: 12,
        elevation: 8,
    },
    thumbnail: {
        width: 50,
        height: 50,
        borderRadius: 25,
    },

    actionsRow: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        gap: 20,
    },
    actionGroup: {
        alignItems: "center",
        flex: 1,
    },
    sectionLabel: {
        fontSize: 10,
        color: "rgba(255,255,255,0.5)",
        fontWeight: "700",
        letterSpacing: 1.5,
        marginBottom: 8,
    },
    costumesList: {
        gap: 10,
        alignItems: "center",
        justifyContent: "flex-start",
        flexDirection: "row",
    },
    costumeItemSkeleton: {
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: "rgba(255,255,255,0.2)",
    },
    costumeItem: {
        width: 42,
        height: 42,
        borderRadius: 21,
        padding: 2,
        borderWidth: 2,
        borderColor: "transparent",
        backgroundColor: "rgba(255,255,255,0.05)",
    },
    costumeItemActive: { borderColor: "#FF6FA5", backgroundColor: "rgba(255, 111, 165, 0.15)" },
    costumeThumb: { width: 34, height: 34, borderRadius: 17 },
    danceBtn: {
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "rgba(255, 255, 255, 0.1)",
        width: 42,
        height: 42,
        borderRadius: 21,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.15)",
    },

    // Features
    featuresContainer: { gap: 14 },
    featureItem: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255,255,255,0.05)",
        padding: 12,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.05)",
    },
    featureItemHighlight: {
        backgroundColor: "rgba(242,193,78,0.12)",
        borderColor: "rgba(242,193,78,0.45)",
    },
    featureTextHighlight: { color: "#FFE0A3", fontWeight: "800" },
    x2Pill: {
        marginLeft: "auto",
        backgroundColor: "#F2C14E",
        borderRadius: 10,
        paddingHorizontal: 8,
        paddingVertical: 2,
    },
    x2PillText: { color: "#2A1A00", fontSize: 12.5, fontWeight: "900" },
    featureIcon: {
        width: 36,
        height: 36,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 14,
    },
    featureText: { color: "#fff", fontSize: 15, fontWeight: "600", flex: 1 },

    // Bottom panel
    bottomPanel: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        paddingTop: 24,
        paddingHorizontal: 24,
        overflow: "hidden",
        backgroundColor: "rgba(12,7,22,0.97)",
    },
    bottomFade: {
        position: "absolute",
        left: 0,
        right: 0,
        bottom: 0,
        height: 480,
    },
    plansRow: { flexDirection: "row", gap: 12, marginBottom: 20 },
    planCard: {
        flex: 1,
        backgroundColor: "rgba(255,255,255,0.08)",
        borderRadius: 20,
        padding: 16,
        borderWidth: 1.5,
        borderColor: "rgba(255,255,255,0.1)",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        position: "relative",
    },
    planCardSelected: { borderColor: "#FF6FA5", backgroundColor: "rgba(255, 111, 165,0.1)" },
    planInfo: { flex: 1 },
    planName: {
        color: "rgba(255,255,255,0.6)",
        fontSize: 12,
        fontWeight: "700",
        marginBottom: 4,
    },
    textHL: { color: "#a78bfa" },
    planPrice: { color: "#fff", fontSize: 18, fontWeight: "700" },
    perMonth: { color: "rgba(255,255,255,0.5)", fontSize: 12, marginTop: 2 },
    radio: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: "rgba(255,255,255,0.3)",
    },
    radioSelected: { borderColor: "#FF6FA5", backgroundColor: "#FF6FA5" },
    discountBadge: {
        position: "absolute",
        top: -10,
        right: 12,
        backgroundColor: "#4CAF50",
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 8,
    },
    discountText: { color: "#fff", fontSize: 10, fontWeight: "800" },

    // CTA
    ctaButton: {
        borderRadius: 28,
        overflow: "hidden",
        marginBottom: 16,
        shadowColor: "#FF6FA5",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 8,
    },
    ctaGradient: { paddingVertical: 18, alignItems: "center", justifyContent: "center" },
    ctaText: { color: "#fff", fontSize: 18, fontWeight: "bold", letterSpacing: 0.5 },

    // Footer
    footerLinks: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        opacity: 0.7,
    },
    footerLink: { color: "#fff", fontSize: 12, fontWeight: "500" },
    footerDot: { color: "#fff", marginHorizontal: 10, fontSize: 10 },

    // Active plan states
    planCardActive: {
        borderColor: "rgba(245, 158, 11, 0.5)",
        backgroundColor: "rgba(245, 158, 11, 0.08)",
    },
    activeBadge: {
        position: "absolute",
        top: -10,
        right: 12,
        backgroundColor: "#F59E0B",
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 8,
    },
    activeText: { color: "#fff", fontSize: 10, fontWeight: "800" },
    textActive: { color: "#F59E0B" },

    // Manage subscription CTA
    ctaButtonManage: {
        borderRadius: 28,
        borderWidth: 1.5,
        borderColor: "rgba(255,255,255,0.15)",
        paddingVertical: 18,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 16,
    },
    ctaTextManage: { color: "rgba(255,255,255,0.7)", fontSize: 16, fontWeight: "600" },
});
